--- # Start

--- # change port
server:
  port: 8085

--- # Thymeleaf
spring:
  thymeleaf:
    cache: false # reload
    prefix: file:src/main/resources/templates # classpath:/templates
    suffix: .html

--- # mariadb
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/boot_study
    username: boot
    password: boot
    hikari:
      auto-commit: true

--- # Sql format
spring:
  jpa:
    hibernate.ddl-auto: none #update
    properties.hibernate:
        show_sql: true
        format_sql: true

--- # Logging level : FATAL -> ERROR -> WARN -> INFO - DEBUG - TRACE
logging:
    level:
        org.hibernate.type.descriptor.sql: trace
        #com.zaxxer.hikari.HikariConfig: debug
        #com.zaxxer.hikari: trace



--- # Encrypt
encrypt:
  key16: ABCdefg123456plm