--- # 문서의 시작
--- # Port
server:
  port: 8085

--- # MariaDB
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/boot_study
    username: boot
    password: boot

--- # Thymeleaf
spring:
  thymeleaf:
    cache: false
    #spring.thymeleaf.prefix=classpath:/templates
    prefix: file:src/main/resources/templates
    suffix: .html

--- # Dev
spring:
  devtools:
    livereload.enabled: true

--- #mybatis mapper xml
mybatis:
  mapper-locations: classpath:sqlmapper/*.xml
  configuration:
    map-underscore-to-camel-case: true