--- # 문서의 시작
--- # Port
server:
  port: 8085

--- # MariaDB
spring:
  first-db:
    datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3307/boot_study
      username: boot
      password: boot
      maximum-pool-size: 5
#      hikari:
#        maximum-pool-size: 5

  second-db:
    datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3307/bootex
      username: bootex
      password: bootex
      maximum-pool-size: 3
#      hikari:
#        maximum-pool-size: 5

  oracle-db:
    datasource:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@localhost:1521/xe
      username: scott
      password: tiger
      maximum-pool-size: 2
#      hikari:
#        maximum-pool-size: 5

#    hikari:
#      auto-commit: true
#      maximum-pool-size: 5

--- # Thymeleaf
spring:
  thymeleaf:
    cache: false
    #spring.thymeleaf.prefix=classpath:/templates
    prefix: file:src/main/resources/templates
    suffix: .html

--- # Dev
spring:
  devtools:
    livereload.enabled: true

--- #mybatis mapper xml
mybatis:
  mapper-locations: classpath:sqlmapper/*.xml
  configuration:
    map-underscore-to-camel-case: false