--- # Port
server:
  port: 8085

--- # MariaDB
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/boot_study
    username: boot
    password: boot

--- # Thymeleaf
spring:
  thymeleaf:
    cashe: false
    prefix: classpath:/templates
    suffix: .html

--- # Dev
spring:
  devtools:
    livereload:
      enabled: true

#mybatis mapper xml
mybatis:
  mapper-locations: classpath:sqlmapper/**/*.xml
#  configuration:
#    map-underscore-to-camel-case: true