--- # Start

--- # change port
server:
  port: 8085

--- # Thymeleaf
spring:
  thymeleaf:
    cache: false # 소스 자동 반영
    prefix: classpath:/templates/ # file:src/main/resources/templates
    suffix: .html

--- # mariadb
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/bootex
    username: bootuser
    password: bootuser

--- #
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
