--- # 문서의 시작

# change port
server:
  port: 8085

--- # Thymeleaf
spring:
  thymeleaf:
    cache: false # reload
    prefix: file:src/main/resources/templates # classpath:/templates
    suffix: .html

--- # mariadb
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/boot_study
    username: boot
    password: boot

--- # devtools
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

... # 문서의 끝
