--- # 문서의 시작

--- # Port
server:
  port: 8085

--- # Thymeleaf
spring:
  thymeleaf:
    cache: false

--- #spring.thymeleaf.prefix=classpath:/templates
spring:
  thymeleaf:
    prefix: file:src/main/resources/templates
    suffix: .html

--- # Dev Configuration
spring:
  devtools:
    livereload:
      enabled: true

--- # MariaDb
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/boot_study
    username: boot
    password: boot
    #hikari:
     # auto-commit: false

--- #mybatis mapper xml
mybatis:
  mapper-locations: classpath:sqlmapper/*.xml
  configuration:
    map-underscore-to-camel-case: false

... # 문서의 끝